apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: catalog-search
  labels:
    app: frontend
    component: web
data:
  # Application Environment
  VITE_APP_ENV: "production"
  VITE_APP_NAME: "AI-Powered Product Catalog Search"
  
  # API Configuration
  VITE_API_BASE_URL: "https://api.productcatalog.com/api/v1"
  VITE_WEBSOCKET_URL: "wss://api.productcatalog.com/ws"
  VITE_AUTH_DOMAIN: "auth.productcatalog.com"
  
  # Feature Flags
  VITE_ENABLE_ANALYTICS: "true"
  VITE_ENABLE_SENTRY: "true"
  VITE_ENABLE_CACHE: "true"
  
  # Performance and Limits
  VITE_MAX_FILE_SIZE: "10485760"  # 10MB in bytes
  VITE_API_TIMEOUT: "30000"       # 30 seconds in milliseconds
  VITE_RETRY_ATTEMPTS: "3"        # Number of API retry attempts
  VITE_CACHE_TTL: "86400"        # 24 hours in seconds