# Kubernetes HPA configuration for frontend application
# Using autoscaling/v2 API version (Kubernetes v1.25+)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: catalog-search
  labels:
    app: frontend
    component: web
    tier: frontend
    managed-by: kubernetes
  annotations:
    description: "HPA for frontend React application"
    scaling-policy: "conservative"

spec:
  # Target the frontend deployment for scaling
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend

  # Scaling limits based on requirements
  minReplicas: 2
  maxReplicas: 10

  # Resource metrics for scaling decisions
  metrics:
    # CPU-based scaling
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

    # Memory-based scaling
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

  # Scaling behavior configuration for production stability
  behavior:
    # Scale up configuration
    scaleUp:
      # Wait 60 seconds before scaling up again
      stabilizationWindowSeconds: 60
      policies:
        # Add up to 2 pods every 60 seconds
        - type: Pods
          value: 2
          periodSeconds: 60
      selectPolicy: Max

    # Scale down configuration
    scaleDown:
      # Wait 300 seconds before scaling down
      stabilizationWindowSeconds: 300
      policies:
        # Remove 1 pod every 120 seconds
        - type: Pods
          value: 1
          periodSeconds: 120
      selectPolicy: Min