apiVersion: v1
kind: Secret
metadata:
  name: frontend-secrets
  namespace: catalog-search
  labels:
    app: frontend
    component: web
    environment: production
    managed-by: terraform
    security-tier: restricted
  annotations:
    secret-rotation: enabled
    vault.hashicorp.com/agent-inject: "true"
    azure-key-vault-env-injection: enabled
type: Opaque
data:
  # Azure AD B2C Authentication Configuration
  # Client ID for OAuth 2.0 authentication - Rotated yearly
  VITE_AUTH_CLIENT_ID: ${base64_client_id}

  # Client Secret for OAuth 2.0 flow - Rotated quarterly
  VITE_AUTH_CLIENT_SECRET: ${base64_client_secret}

  # Tenant ID for Azure AD B2C - Static value
  VITE_AUTH_TENANT_ID: ${base64_tenant_id}

  # Application Monitoring & Analytics
  # Sentry Error Tracking DSN - Rotated yearly
  VITE_SENTRY_DSN: ${base64_sentry_dsn}

  # Analytics API Key - Rotated every 6 months
  VITE_ANALYTICS_KEY: ${base64_analytics_key}

  # Security & Encryption
  # Backend API Authentication Key - Rotated quarterly
  VITE_API_KEY: ${base64_api_key}

  # Client-side Encryption Key - Rotated every 6 months
  VITE_ENCRYPTION_KEY: ${base64_encryption_key}

  # JWT Verification Public Key - Rotated yearly
  VITE_JWT_PUBLIC_KEY: ${base64_jwt_public_key}