# Kubernetes RBAC Configuration v1.25+
# Purpose: Define comprehensive role-based access control policies for AI-powered Product Catalog Search System
# Security Compliance: SOC 2 Type II and ISO 27001 standards
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: product-search
  labels:
    app: ai-catalog-search
    component: backend
    security-monitoring: enabled
    compliance: soc2-iso27001
rules:
  # Backend service permissions
  - apiGroups: [""]
    resources: ["secrets", "configmaps", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: frontend-role
  namespace: product-search
  labels:
    app: ai-catalog-search
    component: frontend
    security-monitoring: enabled
    compliance: soc2-iso27001
rules:
  # Frontend service permissions (minimal required access)
  - apiGroups: [""]
    resources: ["configmaps", "services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: celery-role
  namespace: product-search
  labels:
    app: ai-catalog-search
    component: worker
    security-monitoring: enabled
    compliance: soc2-iso27001
rules:
  # Celery worker permissions
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
  namespace: product-search
  labels:
    app: ai-catalog-search
    component: backend
    security-monitoring: enabled
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend-role
subjects:
  - kind: ServiceAccount
    name: backend-sa
    namespace: product-search
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: frontend-rolebinding
  namespace: product-search
  labels:
    app: ai-catalog-search
    component: frontend
    security-monitoring: enabled
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: frontend-role
subjects:
  - kind: ServiceAccount
    name: frontend-sa
    namespace: product-search
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: celery-rolebinding
  namespace: product-search
  labels:
    app: ai-catalog-search
    component: worker
    security-monitoring: enabled
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: celery-role
subjects:
  - kind: ServiceAccount
    name: celery-sa
    namespace: product-search