# Kubernetes v1.25+
# Service Account configuration for AI-powered Product Catalog Search System
# Implements security controls, RBAC integration, and SOC2/ISO27001 compliance

---
# Backend Service Account with restricted access and enhanced security monitoring
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: product-search
  labels:
    app: ai-catalog-search
    component: backend
    security-monitoring: enabled
    security-tier: restricted
    compliance-level: high
  annotations:
    description: "Service account for backend API service with restricted access"
    compliance: soc2-iso27001
    security.io/monitored: "true"
    audit.io/enabled: "true"
    rotation.io/enabled: "true"
    rotation.io/frequency: "30d"

---
# Frontend Service Account with standard access and security monitoring
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: product-search
  labels:
    app: ai-catalog-search
    component: frontend
    security-monitoring: enabled
    security-tier: standard
    compliance-level: medium
  annotations:
    description: "Service account for frontend web service with standard access"
    compliance: soc2-iso27001
    security.io/monitored: "true"
    audit.io/enabled: "true"
    rotation.io/enabled: "true"
    rotation.io/frequency: "45d"

---
# Celery Worker Service Account with restricted access and enhanced security monitoring
apiVersion: v1
kind: ServiceAccount
metadata:
  name: celery-sa
  namespace: product-search
  labels:
    app: ai-catalog-search
    component: worker
    security-monitoring: enabled
    security-tier: restricted
    compliance-level: high
  annotations:
    description: "Service account for Celery worker service with restricted access"
    compliance: soc2-iso27001
    security.io/monitored: "true"
    audit.io/enabled: "true"
    rotation.io/enabled: "true"
    rotation.io/frequency: "30d"