apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: catalog-search
  labels:
    app: redis
    tier: cache
    component: security
    managed-by: manual
    rotation-schedule: 90-days
  annotations:
    # Track secret rotation schedule
    rotation.kubernetes.io/last-rotated: "2024-01-20T00:00:00Z"  # Update with actual rotation date
    encryption.kubernetes.io/key-type: "AES-256"
    tls.kubernetes.io/validity: "1-year"
    security.kubernetes.io/monitored: "true"
    # Additional security annotations
    vault.security.io/key-source: "azure-key-vault"
    security.io/compliance-validated: "true"
    backup.kubernetes.io/enabled: "true"
    audit.kubernetes.io/enabled: "true"

type: Opaque

# Base64 encoded sensitive data
# Note: Values below are placeholders and should be replaced with actual secure values
data:
  # Redis authentication password (32+ chars, mixed case, numbers, special chars)
  redis-password: "QWRtaW4xMjMhQCMkJV4mKigpXy0rPUBzZWN1cmVfcmVkaXNfcGFzc3dvcmQ="
  
  # AES-256 encryption key for data at rest
  encryption-key: "NEd4OWpwMlhKV2RVdkJYdXF5TmJXbkVmUmNHeVRoTXFQc0x5WnZhQXRLdz0="
  
  # TLS certificate for secure communication
  tls-cert: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVJakNDQXdxZ0F3SUJBZ0lVTXlBd0VnWURWUVFERXd0eVpXUnBjeTVzYjJOaGJEQWVGdzB5TkRBeE1UQXgKTWpBd01EQmFGdzB5TlRBeE1Ua3hNakF3TURCYU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQgpDZ0tDQVFFQXhYRjRZWE56YVc1bklHaDBkSEJ6T2k4dkxpOHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2Ckx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHUKTFM4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dgpMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2Ckx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHUKTFM4dkx5OD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  
  # Private key for TLS certificate
  tls-key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRREZjWGhoYzNOcGJtY2cKYUhSMGNITTZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dgpMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkxTOHZMeTh2THk4dkx5OHZMeTh2Ckx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHZMeTh2THk4dkx5OHUKTFM4dkx5OD0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo="