apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: catalog-search
  labels:
    app: redis
    tier: cache
    component: security
    managed-by: manual
    rotation-schedule: 90-days
  annotations:
    # Track secret rotation schedule
    rotation.kubernetes.io/last-rotated: "2024-01-20T00:00:00Z"  # Updated during rotation
    encryption.kubernetes.io/key-type: "AES-256"
    tls.kubernetes.io/validity: "1-year"
    security.kubernetes.io/monitored: "true"

type: Opaque

# All sensitive values are base64 encoded as per Kubernetes requirements
data:
  # High complexity password: 32+ chars, special chars, numbers, mixed case
  redis-password: "QWJjMTIzISRAIyRfTG9uZ19Db21wbGV4X1Bhc3N3b3JkX0ZvclJlZGlzXzEyMyFAIyQ="
  
  # AES-256 encryption key for data at rest
  encryption-key: "RDc4NUYxMjM0QUI5ODc2NTQzMjFGRUVEQ0JBOTg3NjU0MzIxREM0NTY3ODkwQUJDREVGMTIzNDU2Nzg5MA=="
  
  # TLS certificate for secure communication (X.509)
  tls-cert: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVJakNDQXdxZ0F3SUJBZ0lVTXpZeE5qTTJOVFl6TmpjNE16WXhOak0yTlRZPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
  
  # RSA-2048 private key for TLS (protected by HSM)
  tls-key: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBekc3RHJZK2VaQT09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t"