apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: catalog-search
  labels:
    app: redis
    tier: cache
    component: database
    managed-by: kubernetes
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    description: "Headless service for Redis StatefulSet DNS-based discovery"
spec:
  # Headless service configuration with no ClusterIP
  clusterIP: None
  # Allow DNS resolution for pods not ready
  publishNotReadyAddresses: true
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  # Label selector for Redis pods
  selector:
    app: redis
    tier: cache