# Kubernetes Ingress resource for backend FastAPI service
# External dependency: networking.k8s.io/v1 (Kubernetes v1.25+)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: product-search
  annotations:
    # Azure Application Gateway Ingress Controller configuration
    kubernetes.io/ingress.class: "azure/application-gateway"
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
    appgw.ingress.kubernetes.io/request-timeout: "30"
    appgw.ingress.kubernetes.io/waf-policy-for-path: "waf-policy-product-search"
    
    # NGINX-specific configurations for additional security and performance
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    
    # TLS certificate management
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  # TLS configuration for HTTPS
  tls:
    - hosts:
        - api.product-search.example.com
      secretName: tls-secret
  
  # Routing rules
  rules:
    - host: api.product-search.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8000