apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: product-search
  labels:
    app: backend
    component: api
    environment: production
    security-tier: high
    compliance: soc2-iso27001
    rotation-schedule: 30-days
  annotations:
    azure.key-vault/enabled: "true"
    azure.key-vault/rotation-poll-interval: "1h"
    security.vault.hashicorp.com/key-rotation: "enabled"
    security.azure.com/encryption-at-rest: "aes256"
    security.azure.com/key-version: "v1"
    security.azure.com/hsm-backed: "true"
    security.azure.com/auto-rotation: "enabled"
    security.azure.com/audit-logging: "enabled"
    security.azure.com/compliance-validated: "soc2-iso27001"
type: Opaque
data:
  # Database Credentials - 30 day rotation
  DATABASE_USERNAME: <base64_encoded>
  DATABASE_PASSWORD: <base64_encoded>

  # Azure Service Credentials - 90 day rotation
  AZURE_CLIENT_ID: <base64_encoded>
  AZURE_CLIENT_SECRET: <base64_encoded>
  AZURE_TENANT_ID: <base64_encoded>
  AZURE_SUBSCRIPTION_ID: <base64_encoded>
  AZURE_STORAGE_CONNECTION_STRING: <base64_encoded>
  AZURE_KEYVAULT_URL: <base64_encoded>

  # Data Store Credentials - 30 day rotation
  COSMOS_DB_KEY: <base64_encoded>
  REDIS_PASSWORD: <base64_encoded>

  # Security Tokens - 30 day rotation
  JWT_SECRET_KEY: <base64_encoded>
  OAUTH_CLIENT_ID: <base64_encoded>
  OAUTH_CLIENT_SECRET: <base64_encoded>

  # External API Keys - 60 day rotation
  OPENAI_API_KEY: <base64_encoded>
  NVIDIA_API_KEY: <base64_encoded>