version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        NODE_VERSION: '18.18.0'
        NGINX_VERSION: '1.25.3'
    container_name: ai-catalog-web-dev
    ports:
      - "3000:3000"  # React development server
      - "24678:24678"  # Vite HMR websocket
    volumes:
      - .:/app:cached  # Mount source code
      - node_modules:/app/node_modules  # Named volume for node_modules
      - build:/app/build  # Named volume for build artifacts
    environment:
      - NODE_ENV=development
      - VITE_MODE=development
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
      - VITE_WS_URL=ws://localhost:8000/ws
      - VITE_ENABLE_DEVTOOLS=true
      - VITE_ENABLE_DEBUG=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_APP_VERSION=1.0.0
      - VITE_STORAGE_ENCRYPTION_KEY=dev_secure_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge
    name: ai_catalog_dev_net
    driver_opts:
      com.docker.network.bridge.name: app_dev_net
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

volumes:
  node_modules:
    name: ai_catalog_web_node_modules
  build:
    name: ai_catalog_web_build