apiVersion: v1
kind: ConfigMap
metadata:
  name: celery-configmap
  namespace: catalog-search
  labels:
    app: celery
    component: config
    environment: production
data:
  # Broker and Backend Configuration
  # Redis service connection for message broker and result backend (v6.0+)
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"
  
  # Serialization Settings
  CELERY_TASK_SERIALIZER: "json"
  CELERY_RESULT_SERIALIZER: "json"
  CELERY_ACCEPT_CONTENT: "['json']"
  
  # Task Execution Limits
  # Soft timeout (1 hour) and hard timeout (2 hours) for task execution
  CELERY_TASK_SOFT_TIME_LIMIT: "3600"
  CELERY_TASK_TIME_LIMIT: "7200"
  
  # Worker Performance Settings
  CELERY_WORKER_PREFETCH_MULTIPLIER: "4"
  CELERY_TASK_TRACK_STARTED: "true"
  
  # Queue Routing Configuration
  CELERY_TASK_ROUTES: "{
    \"app.tasks.document_tasks.*\": {\"queue\": \"document\"},
    \"app.tasks.embedding_tasks.*\": {\"queue\": \"embedding\"},
    \"app.tasks.notification_tasks.*\": {\"queue\": \"notification\"}
  }"
  CELERY_TASK_QUEUES: "document,embedding,notification"
  CELERY_TASK_DEFAULT_QUEUE: "default"
  
  # Worker Resource Management
  CELERY_WORKER_MAX_TASKS_PER_CHILD: "1000"
  CELERY_WORKER_MAX_MEMORY_PER_CHILD: "400000"
  CELERY_WORKER_CONCURRENCY: "8"
  CELERY_WORKER_POOL: "prefork"
  
  # Logging and Monitoring
  CELERY_LOG_LEVEL: "info"
  CELERY_WORKER_SEND_TASK_EVENTS: "true"
  CELERY_TASK_SEND_SENT_EVENT: "true"
  CELERY_WORKER_HIJACK_ROOT_LOGGER: "false"
  
  # External Service Credentials
  # These values will be replaced by actual secrets in production
  AZURE_STORAGE_CONNECTION_STRING: "${AZURE_STORAGE_CONNECTION}"
  AZURE_OPENAI_API_KEY: "${AZURE_OPENAI_API_KEY}"
  NVIDIA_OCR_API_KEY: "${NVIDIA_OCR_API_KEY}"