apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: catalog-search
  labels:
    app: celery
    component: worker
    tier: backend
    environment: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: celery
      component: worker
  template:
    metadata:
      labels:
        app: celery
        component: worker
        tier: backend
        environment: production
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      containers:
      - name: celery-worker
        image: catalog-search/backend:latest
        imagePullPolicy: Always
        command:
        - celery
        - -A
        - app.tasks.celery_app
        - worker
        - --loglevel=info
        - --concurrency=4
        - --max-tasks-per-child=1000
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        envFrom:
        - configMapRef:
            name: celery-configmap
        - secretRef:
            name: celery-secrets
        livenessProbe:
          exec:
            command:
            - celery
            - -A
            - app.tasks.celery_app
            - inspect
            - ping
            - -d
            - celery@$HOSTNAME
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - celery
            - -A
            - app.tasks.celery_app
            - inspect
            - ping
            - -d
            - celery@$HOSTNAME
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      terminationGracePeriodSeconds: 60
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000