apiVersion: v1
kind: Secret
metadata:
  name: celery-secrets
  namespace: catalog-search
  labels:
    app: celery
    component: secrets
    environment: ${ENV}
    managed-by: terraform
  annotations:
    azure.key-vault/secret-rotation: "enabled"
    azure.key-vault/rotation-poll-interval: "1h"
    security.kubernetes.io/last-rotation: ${TIMESTAMP}
type: Opaque
data:
  # Azure Storage connection string for document storage
  AZURE_STORAGE_CONNECTION: ${BASE64_AZURE_STORAGE_CONNECTION}
  
  # Azure OpenAI API key for GPT-4 integration
  AZURE_OPENAI_API_KEY: ${BASE64_AZURE_OPENAI_API_KEY}
  
  # NVidia OCR API key for document processing
  NVIDIA_OCR_API_KEY: ${BASE64_NVIDIA_OCR_API_KEY}
  
  # Redis credentials for caching
  REDIS_PASSWORD: ${BASE64_REDIS_PASSWORD}
  
  # Celery broker (RabbitMQ/Redis) authentication
  CELERY_BROKER_PASSWORD: ${BASE64_CELERY_BROKER_PASSWORD}
  
  # Celery result backend (Redis) authentication
  CELERY_RESULT_BACKEND_PASSWORD: ${BASE64_CELERY_RESULT_BACKEND_PASSWORD}