apiVersion: v1
kind: Service
metadata:
  name: celery-worker
  namespace: catalog-search
  labels:
    app: celery
    component: worker
    tier: backend
    part-of: catalog-search
    managed-by: kubernetes
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9901"
    prometheus.io/path: "/metrics"
    monitoring.kubernetes.io/description: "Celery worker monitoring endpoints"
    service.kubernetes.io/topology-aware-hints: "auto"

spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9901
      targetPort: 9901
      protocol: TCP
    - name: flower
      port: 5555
      targetPort: 5555
      protocol: TCP
  selector:
    app: celery
    component: worker
  sessionAffinity: None
  internalTrafficPolicy: Cluster