name: Deploy to Development

on:
  workflow_run:
    workflows: ['Backend CI', 'Frontend CI']
    types: [completed]
    branches: [develop]
  workflow_dispatch:
    inputs:
      deploy_frontend:
        type: boolean
        default: true
        description: 'Deploy frontend service'
      deploy_backend:
        type: boolean
        default: true
        description: 'Deploy backend service'
      skip_health_check:
        type: boolean
        default: false
        description: 'Skip deployment health verification'

env:
  ENVIRONMENT: development
  NAMESPACE: catalog-search-dev
  DEPLOYMENT_TIMEOUT: 600s
  HEALTH_CHECK_RETRIES: 5

concurrency:
  group: development
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Services
    runs-on: ubuntu-latest
    environment:
      name: development
      url: https://dev.catalog-search.example.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
          resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}

      - name: Create namespace if not exists
        run: |
          kubectl get namespace ${{ env.NAMESPACE }} || kubectl create namespace ${{ env.NAMESPACE }}

      - name: Validate GPU nodes
        run: |
          GPU_NODES=$(kubectl get nodes -l nvidia.com/gpu=true -o name)
          if [ -z "$GPU_NODES" ]; then
            echo "Error: No GPU nodes found in the cluster"
            exit 1
          fi

      - name: Deploy backend service
        if: ${{ github.event.inputs.deploy_backend != 'false' }}
        uses: azure/k8s-deploy@v4
        with:
          namespace: ${{ env.NAMESPACE }}
          manifests: |
            infrastructure/kubernetes/backend/deployment.yaml
          images: |
            ${{ needs.backend-ci.outputs.docker-image }}:${{ needs.backend-ci.outputs.image-tag }}
          timeout: ${{ env.DEPLOYMENT_TIMEOUT }}
          strategy: rolling
          action: deploy

      - name: Deploy frontend service
        if: ${{ github.event.inputs.deploy_frontend != 'false' }}
        uses: azure/k8s-deploy@v4
        with:
          namespace: ${{ env.NAMESPACE }}
          manifests: |
            infrastructure/kubernetes/frontend/deployment.yaml
          images: |
            ${{ needs.frontend-ci.outputs.docker-image }}:${{ needs.frontend-ci.outputs.image-tag }}
          timeout: ${{ env.DEPLOYMENT_TIMEOUT }}
          strategy: rolling
          action: deploy

      - name: Verify deployment health
        if: ${{ github.event.inputs.skip_health_check != 'true' }}
        run: |
          echo "Starting health verification..."
          
          # Backend health check
          if [[ "${{ github.event.inputs.deploy_backend }}" != "false" ]]; then
            RETRIES=${{ env.HEALTH_CHECK_RETRIES }}
            until kubectl rollout status deployment/backend -n ${{ env.NAMESPACE }} --timeout=${{ env.DEPLOYMENT_TIMEOUT }} || [ $RETRIES -eq 0 ]; do
              echo "Waiting for backend deployment... ($RETRIES attempts remaining)"
              RETRIES=$((RETRIES-1))
              sleep 10
            done
            
            # Verify GPU allocation
            GPU_PODS=$(kubectl get pods -n ${{ env.NAMESPACE }} -l app=backend -o jsonpath='{.items[*].status.containerStatuses[*].ready}')
            if [[ ! $GPU_PODS =~ ^(true[ ]*)+$ ]]; then
              echo "Error: Backend pods are not ready or GPU allocation failed"
              exit 1
            fi
          fi
          
          # Frontend health check
          if [[ "${{ github.event.inputs.deploy_frontend }}" != "false" ]]; then
            RETRIES=${{ env.HEALTH_CHECK_RETRIES }}
            until kubectl rollout status deployment/frontend -n ${{ env.NAMESPACE }} --timeout=${{ env.DEPLOYMENT_TIMEOUT }} || [ $RETRIES -eq 0 ]; do
              echo "Waiting for frontend deployment... ($RETRIES attempts remaining)"
              RETRIES=$((RETRIES-1))
              sleep 10
            done
          fi

      - name: Rollback on failure
        if: failure()
        run: |
          echo "Deployment failed, initiating rollback..."
          
          if [[ "${{ github.event.inputs.deploy_backend }}" != "false" ]]; then
            kubectl rollout undo deployment/backend -n ${{ env.NAMESPACE }}
          fi
          
          if [[ "${{ github.event.inputs.deploy_frontend }}" != "false" ]]; then
            kubectl rollout undo deployment/frontend -n ${{ env.NAMESPACE }}
          fi
          
          # Send notification
          if [ ! -z "${{ secrets.DEPLOYMENT_NOTIFICATION_WEBHOOK }}" ]; then
            curl -X POST -H "Content-Type: application/json" \
              -d "{\"text\":\"⚠️ Development deployment failed and rolled back. Environment: ${{ env.ENVIRONMENT }}, Services affected: $([ "${{ github.event.inputs.deploy_backend }}" != "false" ] && echo "backend ")$([ "${{ github.event.inputs.deploy_frontend }}" != "false" ] && echo "frontend")\"}" \
              ${{ secrets.DEPLOYMENT_NOTIFICATION_WEBHOOK }}
          fi

      - name: Deployment success notification
        if: success()
        run: |
          if [ ! -z "${{ secrets.DEPLOYMENT_NOTIFICATION_WEBHOOK }}" ]; then
            curl -X POST -H "Content-Type: application/json" \
              -d "{\"text\":\"✅ Development deployment successful. Environment: ${{ env.ENVIRONMENT }}, Services deployed: $([ "${{ github.event.inputs.deploy_backend }}" != "false" ] && echo "backend ")$([ "${{ github.event.inputs.deploy_frontend }}" != "false" ] && echo "frontend")\"}" \
              ${{ secrets.DEPLOYMENT_NOTIFICATION_WEBHOOK }}
          fi