name: Deploy to Production

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      approval_required:
        description: 'Require manual approval'
        required: true
        default: true
        type: boolean

env:
  ENVIRONMENT: production
  AZURE_CREDENTIALS: ${{ secrets.AZURE_PROD_CREDENTIALS }}
  ACR_NAME: ${{ secrets.PROD_ACR_NAME }}
  PRIMARY_CLUSTER_NAME: ${{ secrets.PROD_PRIMARY_AKS_CLUSTER_NAME }}
  SECONDARY_CLUSTER_NAME: ${{ secrets.PROD_SECONDARY_AKS_CLUSTER_NAME }}
  PRIMARY_RESOURCE_GROUP: ${{ secrets.PROD_PRIMARY_RESOURCE_GROUP }}
  SECONDARY_RESOURCE_GROUP: ${{ secrets.PROD_SECONDARY_RESOURCE_GROUP }}
  TERRAFORM_VERSION: '1.5.0'

permissions:
  id-token: write
  contents: read
  packages: write
  deployments: write
  environments: write

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  deploy-infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://prod.example.com
    timeout-minutes: 120
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Initialize Terraform
        working-directory: infrastructure/terraform/environments/prod
        run: |
          terraform init -backend-config="resource_group_name=${{ env.PRIMARY_RESOURCE_GROUP }}"
          terraform workspace select production || terraform workspace new production

      - name: Plan Infrastructure Changes
        working-directory: infrastructure/terraform/environments/prod
        run: |
          terraform plan -var-file=terraform.tfvars -out=tfplan
          terraform show -json tfplan > tfplan.json

      - name: Manual Approval Gate
        if: github.event.inputs.approval_required == 'true'
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: admin-team
          minimum-approvals: 2
          timeout-minutes: 30

      - name: Apply Infrastructure Changes
        working-directory: infrastructure/terraform/environments/prod
        run: terraform apply -auto-approve tfplan

      - name: Verify Infrastructure Health
        run: |
          az aks get-credentials --resource-group ${{ env.PRIMARY_RESOURCE_GROUP }} --name ${{ env.PRIMARY_CLUSTER_NAME }}
          az aks get-credentials --resource-group ${{ env.SECONDARY_RESOURCE_GROUP }} --name ${{ env.SECONDARY_CLUSTER_NAME }}
          kubectl get nodes --context ${{ env.PRIMARY_CLUSTER_NAME }}
          kubectl get nodes --context ${{ env.SECONDARY_CLUSTER_NAME }}

  build-and-push-images:
    name: Build and Push Images
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: src/backend
          file: src/backend/Dockerfile
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/backend:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.ACR_NAME }}.azurecr.io/backend:cache
          cache-to: type=registry,ref=${{ env.ACR_NAME }}.azurecr.io/backend:cache,mode=max
          build-args: |
            NODE_ENV=production
            API_URL=https://api.example.com

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: src/web
          file: src/web/Dockerfile
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/frontend:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.ACR_NAME }}.azurecr.io/frontend:cache
          cache-to: type=registry,ref=${{ env.ACR_NAME }}.azurecr.io/frontend:cache,mode=max

      - name: Run Trivy Container Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.ACR_NAME }}.azurecr.io/backend:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'
          ignore-unfixed: true

  deploy-to-primary-region:
    name: Deploy to Primary Region
    needs: build-and-push-images
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment:
      name: production
      url: https://prod.example.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group ${{ env.PRIMARY_RESOURCE_GROUP }} --name ${{ env.PRIMARY_CLUSTER_NAME }}

      - name: Deploy with Rolling Update
        run: |
          kubectl apply -f infrastructure/kubernetes/backend/deployment.yaml
          kubectl apply -f infrastructure/kubernetes/frontend/deployment.yaml
          kubectl rollout status deployment/backend -n production
          kubectl rollout status deployment/frontend -n production

      - name: Run Integration Tests
        run: |
          kubectl apply -f infrastructure/kubernetes/tests/integration-tests.yaml
          kubectl wait --for=condition=complete --timeout=300s job/integration-tests -n production

      - name: Verify Deployment Health
        run: |
          kubectl get pods -n production
          kubectl get services -n production
          kubectl get ingress -n production

  deploy-to-secondary-region:
    name: Deploy to Secondary Region
    needs: deploy-to-primary-region
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group ${{ env.SECONDARY_RESOURCE_GROUP }} --name ${{ env.SECONDARY_CLUSTER_NAME }}

      - name: Deploy with Rolling Update
        run: |
          kubectl apply -f infrastructure/kubernetes/backend/deployment.yaml
          kubectl apply -f infrastructure/kubernetes/frontend/deployment.yaml
          kubectl rollout status deployment/backend -n production
          kubectl rollout status deployment/frontend -n production

      - name: Verify Cross-Region Replication
        run: |
          kubectl get pods -n production
          kubectl exec deploy/backend -n production -- curl -f http://localhost:8000/api/v1/health
          kubectl logs deploy/backend -n production --tail=100

      - name: Test Failover Scenarios
        run: |
          kubectl apply -f infrastructure/kubernetes/tests/failover-tests.yaml
          kubectl wait --for=condition=complete --timeout=300s job/failover-tests -n production

      - name: Update Deployment Status
        if: always()
        run: |
          if [[ ${{ job.status }} == 'success' ]]; then
            echo "Deployment completed successfully"
            kubectl annotate deployment backend -n production deployment.kubernetes.io/revision="$(date +%s)"
          else
            echo "Deployment failed, initiating rollback"
            kubectl rollout undo deployment/backend -n production
            kubectl rollout undo deployment/frontend -n production
            exit 1
          fi